- name: docker szolgáltatás engedélyezése 
  service: name=docker enabled=yes

- name: docker szolgáltatás indítása
  service: name=docker state=restarted

- name: rsync telepítése
  apt:
    name: rsync
    state: present

- name: docker-related fájlok másolása a gazdagépre 
  synchronize:
    archive: no
    recursive: yes
    src: "../docker"
    dest: "/"

- name: docker-compose systemd szolgáltatás telepítése
  copy:
    src: "../docker/docker-compose.service"
    dest: "/etc/systemd/system/docker-compose.service"
    owner: root
    group: root
    mode: 0644

- name: docker-compose systemd szolgáltatás indítása
  systemd:
    name: docker-compose.service
    state: restarted
    enabled: yes
    daemon_reload: yes
