---
- name: GIS adatbázis-felhasználó létrehozása
  postgresql_user:
    login_host: localhost
    login_user: postgres

    name: gis
    state: present
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: GIS adatbázis létrehozása
  postgresql_db:
    login_host: localhost
    login_user: postgres

    name: gis
    state: present
    owner: gis

    encoding: UTF-8
    
    template: template_postgis

- name: pgRouting telepítése
  postgresql_ext:
    login_host: localhost
    login_user: postgres

    db: gis
    name: pgrouting
    state: present

- name: Privilégiumok rendezése a GIS adatbázison
  postgresql_privs:
    login_host: localhost
    login_user: postgres

    database: gis
    role: PUBLIC
    type: database
    priv: all
    state: absent
