# Parts from https://github.com/angstwad/docker.ubuntu/blob/master/tasks/main.yml

- name: Add Docker repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: HTTPS APT transport for Docker repository
  apt:
    name: apt-transport-https
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo debian-jessie main" 
    mode: '644'
    update_cache: no
    state: present

- name: Install (or update) docker package
  apt:
    name: docker-engine 
    state: latest 
    update_cache: no

# We must install pip via apt before we can use the pip module below
- name: Install pip, python-dev package with apt
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: no
  with_items:
    - python-dev
    - python-pip
    - python-psycopg2 # Ezt pip helyett apt-ból, hogy felrakja a függőségeit is

- name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - name: pip
    - name: setuptools
    - name: docker-compose==1.9.0
  ignore_errors: yes
