---
- name: /data könyvtárstruktúrájának létrehozása
  file: "path={{ item }} state=directory mode=755"
  with_items:
    - /data
    - /data/osm
    - /data/osm/import_queue
    - /data/osm/import_done
    - /data/osm/settings
    - /data/osm/cache
    - /data/pgdata
    - /data/mapserver

- name: pg_hba.conf másolása
  copy:
    src: "../docker/postgres/pg_hba.conf"
    dest: "/data/pgdata/pg_hba.conf"
    owner: 999
    group: docker
    mode: 0600
